# Generated by Django 4.2.13 on 2024-06-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Total_Expense_Tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Expenses',
            new_name='Expense',
        ),
    ]
