# Generated by Django 4.2.13 on 2024-06-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Total_Expense_Tracker', '0003_remove_expense_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='is_cash',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='is_cash',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='is_cash',
            field=models.BooleanField(),
        ),
    ]
