# Generated by Django 4.2.13 on 2024-06-12 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Total_Expense_Tracker', '0004_alter_expense_is_cash_alter_income_is_cash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 2, 26, 53, 537049, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='income',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 2, 26, 53, 537049, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='shift',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 2, 26, 53, 537049, tzinfo=datetime.timezone.utc)),
        ),
    ]
