# Generated by Django 4.2.13 on 2024-06-12 21:06

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Total_Expense_Tracker', '0006_remove_expense_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 12, 21, 6, 27, 861851, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
