# Generated by Django 4.2.13 on 2024-06-13 02:11

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Total_Expense_Tracker', '0007_expense_date_created_income_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='shift_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 2, 11, 6, 325549, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shift',
            name='hours_worked',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
