# Generated by Django 4.2.13 on 2024-06-14 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Total_Expense_Tracker', '0008_shift_shift_end_shift_shift_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_cash', models.BooleanField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='shift',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_transactions', to='Total_Expense_Tracker.transaction'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip_transactions', to='Total_Expense_Tracker.transaction'),
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
